version: "3.7"

services:
  backup_db:
    build:
      context: ../
    entrypoint: /app/docker/entrypoint.sh
    command: bash -c "./backup_db.rb"
    container_name: "backup_db"
    volumes:
      - ../:/app
      - backup_db_bundle:/bundle
    env_file: ../.env
    environment:
      BUNDLE_PATH: /bundle
      BUNDLE_SILENCE_ROOT_WARNING: 1

  backup_db_bundle:
    image: busybox
    container_name: "backup_db_bundle"
    volumes:
      - backup_db_bundle:/bundle

  backup_db_dockerhost:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
    networks:
      - backend
      - frontend


volumes:
  backup_db_bundle:
