version: "3.7"

services:
  s3backups:
    build:
      context: ../
    entrypoint: /app/docker/entrypoint.sh
    command: bash -c "./s3backups.rb"
    container_name: "s3backups"
    volumes:
      - ../:/app
      - s3backups_bundle:/bundle
    env_file: ../.env
    environment:
      BUNDLE_PATH: /bundle
      BUNDLE_SILENCE_ROOT_WARNING: 1

  s3backups_bundle:
    image: busybox
    container_name: "s3backups_bundle"
    volumes:
      - s3backups_bundle:/bundle

volumes:
  s3backups_bundle:
